on: [push]
jobs:
  jmeter_job:
    runs-on: ubuntu-latest
    name: JMeter TestExecution
    steps:      
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: CreateD
        run: |
           mkdir $./TestPlan2
        
      - name: Run JMeter Tests
        uses: ./
        with:
          test-plan-path: ./TestPlans/Perf_Test_CM_Demo_1.jmx
          args: ""
          
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: result.jtl
